-Hi, I’m @Eddyevagrin2024
- 👀 I’m interested in web development and frontend technologies.
- 🌱 I’m currently learning HTML, CSS, JavaScript, and React.js.
- 💞️ I’m looking to collaborate on open-source web development projects.
- 📫 How to reach me: [Insert your contact info or preferred method of communication].
- 😄 Pronouns: [Insert your preferred pronouns].
- ⚡ Fun fact: I can solve a Rubik's Cube in under two minutes
- 
